import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const raleway = Raleway({
  weight: ["300", "400", "600"],
  variable: "--font-raleway",
  subsets: ["latin", "cyrillic"],
});

const michelin = localFont({
  src: [
    {
      weight: "700",
      path: "../fonts/Michelin-Bold.woff2",
    },
  ],
  variable: "--font-michelin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${michelin.variable} antialiased font-raleway`}
      >
        {children}
      </body>
    </html>
  );
}
